import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod ? "build" : ".";

// Copy plugin assets to build/ and optionally to test vault. Per
// `obsidianmd/no-forbidden-elements`, plugins should not inject `<style>`
// tags at runtime — Obsidian loads `styles.css` automatically. T4.3's
// xterm.js dependency ships its own CSS; we concatenate it into the
// emitted `styles.css` at build time so xterm renders correctly without
// any runtime DOM injection.
const XTERM_CSS = "node_modules/@xterm/xterm/css/xterm.css";

function bundleStylesCss(targetDir) {
	const ours = readFileSync("styles.css", "utf8");
	const xterm = readFileSync(XTERM_CSS, "utf8");
	const out = `${ours}\n\n/* --- @xterm/xterm vendored CSS (T4.3) --- */\n${xterm}\n`;
	writeFileSync(`${targetDir}/styles.css`, out, "utf8");
}

/**
 * Stamp the source manifest with a dev-suffixed version for the test vault
 * so every build looks like a fresh version to Obsidian's plugin loader —
 * defeats stale-module caching during manual QA. Source manifest.json is
 * NEVER modified; the canonical version stays the GitHub release version.
 *
 * Format mirrors miyo-archivist (`obsidian-archivist/esbuild.config.mjs`):
 * `${baseVersion}-dev.${YYYYMMDD-HHmm}`, e.g. "0.0.0-dev.20260428-1620".
 * The `-dev.` is a semver pre-release identifier so it sorts BELOW the
 * canonical version — Obsidian and the Community Plugins manifest both
 * stay clean.
 *
 * Returns the stamped manifest object so the caller can log the version.
 */
function stampManifestForVault() {
	const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
	const baseVersion = manifest.version;
	const stamp = new Date()
		.toISOString()
		.slice(0, 16)
		.replace(/[-:]/g, "")
		.replace("T", "-");
	manifest.version = `${baseVersion}-dev.${stamp}`;
	return manifest;
}

// Stub modules that dockerode pulls transitively but never executes under our
// configuration: `ssh2` and `cpu-features` are only loaded by docker-modem
// when `protocol === "ssh"`. We construct dockerode with an explicit
// `socketPath` (per ADR-1), never an SSH host, so the SSH branch is dead.
//
// `./buildkit` is loaded lazily inside Docker.prototype.followProgress, which
// is the image-build progress streamer. Hashi never builds images — we only
// list/inspect/attach/resize containers — so the buildkit path is unreachable
// in production. Bundling it would pull in protobuf and a large transitive
// graph for code that's literally dead in our use case.
//
// `./session` (issue #46) is required EAGERLY at the top of dockerode's
// docker.js (`withSession = require('./session')`) and in turn top-level
// `require('@grpc/grpc-js')` + `@grpc/proto-loader`, dragging the entire gRPC
// + protobufjs stack (~1 MB pre-minify) into the bundle. `withSession` is only
// ever invoked from `buildImage`'s BuildKit auth flow — which Hashi never
// calls (we only listContainers/getContainer/inspect/attach/resize). Stubbing
// `./session` is the single biggest bundle lever (CON-7 audit): it removes
// @grpc/grpc-js, @grpc/proto-loader, protobufjs, long, lodash.camelcase, and
// @js-sdsl/ordered-map outright.
//
// All of these ship code (or `.node` native binaries) that esbuild cannot bundle
// usefully — and Obsidian plugins ship as a single `main.js` with no adjacent
// `node_modules/`, so externalizing them at runtime fails to resolve. Stubbing
// them at build time bundles dockerode itself into main.js (the only path
// that actually works) while keeping the bundle free of native code.
const stubMissingNativeDeps = {
	name: "stub-missing-native-deps",
	setup(build) {
		build.onResolve({ filter: /^(ssh2|cpu-features)$/ }, (args) => ({
			path: args.path,
			namespace: "stub-empty",
		}));
		// dockerode 4.0.12+: Docker.prototype.followProgress lazy-requires
		// `./buildkit`. Match only when imported FROM dockerode/lib/docker.js
		// so we don't accidentally stub a same-named module elsewhere.
		build.onResolve({ filter: /^\.\/buildkit$/ }, (args) => {
			if (!/dockerode[\\/]lib[\\/]docker\.js$/.test(args.importer)) {
				return null;
			}
			return { path: args.path, namespace: "stub-empty" };
		});
		// dockerode 5.x: docker.js EAGERLY requires `./session` (the gRPC
		// BuildKit session helper), which pulls @grpc/grpc-js + proto-loader +
		// protobufjs (~1 MB pre-minify). withSession is only reached via
		// buildImage, which Hashi never calls. Stub it (issue #46). Same
		// importer guard as buildkit so we only touch dockerode's own module.
		build.onResolve({ filter: /^\.\/session$/ }, (args) => {
			if (!/dockerode[\\/]lib[\\/]docker\.js$/.test(args.importer)) {
				return null;
			}
			return { path: args.path, namespace: "stub-session" };
		});
		build.onLoad({ filter: /.*/, namespace: "stub-empty" }, () => ({
			contents:
				"module.exports = { followProgress: () => { throw new Error('buildkit stubbed — image-build APIs are not used by Hashi'); } };",
			loader: "js",
		}));
		// session.js exports a single function `withSession(docker, auth, handler)`.
		// Keep the shape (a function) so docker.js's top-level binding is valid;
		// throw if it is ever actually invoked (it never is — image build only).
		build.onLoad({ filter: /.*/, namespace: "stub-session" }, () => ({
			contents:
				"module.exports = function withSession() { throw new Error('session/grpc stubbed — image-build (BuildKit) APIs are not used by Hashi'); };",
			loader: "js",
		}));
	},
};

const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			if (prod) {
				mkdirSync("build", { recursive: true });
				copyFileSync("manifest.json", "build/manifest.json");
				bundleStylesCss("build");

				// Optional deployment to the in-repo test vault for manual QA
				// (T5.5b). Set `HASHI_DEPLOY_VAULT=1 npm run build` to enable.
				// Default OFF so CI builds don't trip on a missing vault.
				if (process.env.HASHI_DEPLOY_VAULT) {
					const VAULT_PLUGIN_DIR = "test/Hashi/.obsidian/plugins/miyo-tomo-hashi";
					if (existsSync("test/Hashi/.obsidian")) {
						mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
						copyFileSync(`${outdir}/main.js`, `${VAULT_PLUGIN_DIR}/main.js`);
						const stampedManifest = stampManifestForVault();
						writeFileSync(
							`${VAULT_PLUGIN_DIR}/manifest.json`,
							JSON.stringify(stampedManifest, null, "\t") + "\n",
							"utf8",
						);
						bundleStylesCss(VAULT_PLUGIN_DIR);
						console.log(
							`[deploy] Plugin copied to ${VAULT_PLUGIN_DIR} (version: ${stampedManifest.version})`,
						);
					} else {
						console.warn(
							"[deploy] HASHI_DEPLOY_VAULT set but test/Hashi/.obsidian missing — skipped",
						);
					}
				}

				// Optional deployment to the user's external test vault for
				// real-Obsidian manual QA (T6.4 / ADR-9 v2). Set
				// `HASHI_DEPLOY_PRIVAT=1 npm run build` to enable. Independent
				// of HASHI_DEPLOY_VAULT — both flags can be set together.
				if (process.env.HASHI_DEPLOY_PRIVAT) {
					const PRIVAT_PLUGIN_DIR =
						"../temp/Privat-Test/.obsidian/plugins/miyo-tomo-hashi";
					if (existsSync("../temp/Privat-Test/.obsidian")) {
						mkdirSync(PRIVAT_PLUGIN_DIR, { recursive: true });
						copyFileSync(`${outdir}/main.js`, `${PRIVAT_PLUGIN_DIR}/main.js`);
						const stampedManifest = stampManifestForVault();
						writeFileSync(
							`${PRIVAT_PLUGIN_DIR}/manifest.json`,
							JSON.stringify(stampedManifest, null, "\t") + "\n",
							"utf8",
						);
						bundleStylesCss(PRIVAT_PLUGIN_DIR);
						console.log(
							`[deploy] Plugin copied to ${PRIVAT_PLUGIN_DIR} (version: ${stampedManifest.version})`,
						);
					} else {
						console.warn(
							"[deploy] HASHI_DEPLOY_PRIVAT set but ../temp/Privat-Test/.obsidian missing — skipped",
						);
					}
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// NOTE: dockerode used to be external, but Obsidian plugins ship as a
		// single `main.js` with no `node_modules/` next to it, so external
		// require()s fail at runtime. dockerode is now bundled; its native
		// transitive deps (`ssh2`, `cpu-features`) are stubbed via the
		// `stubMissingNativeDeps` plugin (only used in the SSH transport
		// branch we never hit — we always construct with `socketPath`).
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	// SDD CON-2 + Implementation Gotchas: xterm.js requires a CSS loader for
	// `@xterm/xterm/css/xterm.css`. Use `text` so the CSS is inlined as a string
	// in the single `main.js` artifact (Obsidian plugin packaging model). The
	// xterm CSS will be appended to <head> at view-mount time in phase 4.
	//
	// `.png` → `dataurl`: the settings header inlines the plugin hanko via
	// `import hankoUrl from "../../assets/tomo-hashi-hanko-144.png"`. BRAT
	// and the official Community Plugins installer both fetch only
	// main.js / manifest.json / styles.css from a release, so a sibling
	// `assets/` directory would 404 on non-developer installs. Inlining as
	// a data URI is the only delivery path that survives both installers.
	loader: { ".css": "text", ".png": "dataurl" },
	plugins: [stubMissingNativeDeps, copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
