import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";
import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = prod ? "build" : ".";

// Copy plugin assets to build/ and optionally to test vault. Per
// `obsidianmd/no-forbidden-elements`, plugins should not inject `<style>`
// tags at runtime — Obsidian loads `styles.css` automatically. T4.3's
// xterm.js dependency ships its own CSS; we concatenate it into the
// emitted `styles.css` at build time so xterm renders correctly without
// any runtime DOM injection.
const XTERM_CSS = "node_modules/@xterm/xterm/css/xterm.css";

function bundleStylesCss(targetDir) {
	const ours = readFileSync("styles.css", "utf8");
	const xterm = readFileSync(XTERM_CSS, "utf8");
	const out = `${ours}\n\n/* --- @xterm/xterm vendored CSS (T4.3) --- */\n${xterm}\n`;
	writeFileSync(`${targetDir}/styles.css`, out, "utf8");
}

// Stub modules that dockerode pulls transitively but never executes under our
// configuration: `ssh2` and `cpu-features` are only loaded by docker-modem
// when `protocol === "ssh"`. We construct dockerode with an explicit
// `socketPath` (per ADR-1), never an SSH host, so the SSH branch is dead.
//
// Both modules ship `.node` native binaries that esbuild cannot bundle — and
// Obsidian plugins ship as a single `main.js` with no adjacent `node_modules/`,
// so externalizing them at runtime fails to resolve. Stubbing them out at
// build time bundles dockerode itself into main.js (the only path that
// actually works) while keeping the bundle free of native code.
const stubMissingNativeDeps = {
	name: "stub-missing-native-deps",
	setup(build) {
		build.onResolve({ filter: /^(ssh2|cpu-features)$/ }, (args) => ({
			path: args.path,
			namespace: "stub-empty",
		}));
		build.onLoad({ filter: /.*/, namespace: "stub-empty" }, () => ({
			contents: "module.exports = {};",
			loader: "js",
		}));
	},
};

const copyAssets = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			if (prod) {
				mkdirSync("build", { recursive: true });
				copyFileSync("manifest.json", "build/manifest.json");
				bundleStylesCss("build");

				// Optional deployment to the in-repo test vault for manual QA
				// (T5.5b). Set `HASHI_DEPLOY_VAULT=1 npm run build` to enable.
				// Default OFF so CI builds don't trip on a missing vault.
				if (process.env.HASHI_DEPLOY_VAULT) {
					const VAULT_PLUGIN_DIR = "test/Hashi/.obsidian/plugins/miyo-tomo-hashi";
					if (existsSync("test/Hashi/.obsidian")) {
						mkdirSync(VAULT_PLUGIN_DIR, { recursive: true });
						copyFileSync(`${outdir}/main.js`, `${VAULT_PLUGIN_DIR}/main.js`);
						copyFileSync("manifest.json", `${VAULT_PLUGIN_DIR}/manifest.json`);
						bundleStylesCss(VAULT_PLUGIN_DIR);
						console.log(`[deploy] Plugin copied to ${VAULT_PLUGIN_DIR}`);
					} else {
						console.warn(
							"[deploy] HASHI_DEPLOY_VAULT set but test/Hashi/.obsidian missing — skipped",
						);
					}
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		// NOTE: dockerode used to be external, but Obsidian plugins ship as a
		// single `main.js` with no `node_modules/` next to it, so external
		// require()s fail at runtime. dockerode is now bundled; its native
		// transitive deps (`ssh2`, `cpu-features`) are stubbed via the
		// `stubMissingNativeDeps` plugin (only used in the SSH transport
		// branch we never hit — we always construct with `socketPath`).
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	// SDD CON-2 + Implementation Gotchas: xterm.js requires a CSS loader for
	// `@xterm/xterm/css/xterm.css`. Use `text` so the CSS is inlined as a string
	// in the single `main.js` artifact (Obsidian plugin packaging model). The
	// xterm CSS will be appended to <head> at view-mount time in phase 4.
	loader: { ".css": "text" },
	plugins: [stubMissingNativeDeps, copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
